'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbLujan21Entities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbLujan21Entities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Property tblAdmi() As DbSet(Of tblAdmi)
    Public Property tblCliente() As DbSet(Of tblCliente)
    Public Property tblExtras() As DbSet(Of tblExtras)
    Public Property tblLavados() As DbSet(Of tblLavados)
    Public Property tblPaquetes() As DbSet(Of tblPaquetes)
    Public Property tblVehiculo() As DbSet(Of tblVehiculo)

End Class
