'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblAdmi
    Public Property admiId As Integer
    Public Property admiNombre As String
    Public Property admiApellidos As String
    Public Property admiUsuario As String
    Public Property admiPW As String
    Public Property admiRights As String

End Class
