'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCliente
    Public Property clienId As Integer
    Public Property clienPlacaVehiculo As Nullable(Of Integer)
    Public Property clienNombre As String
    Public Property clienApellidos As String
    Public Property clienTelefono As String

    Public Overridable Property tblLavados As ICollection(Of tblLavados) = New HashSet(Of tblLavados)
    Public Overridable Property tblVehiculo As tblVehiculo

End Class
