'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblCitas
    Public Property citId As Integer
    Public Property citNombre As String
    Public Property citApellidos As String
    Public Property citPlaca As String
    Public Property citMarca As String
    Public Property citFecha As Date
    Public Property citHora As String
    Public Property citTelefono As String
    Public Property citDescrip As String

End Class
