'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblLavados
    Public Property lavConsecutivo As Integer
    Public Property lavFecha As Date
    Public Property lavIdCliente As Integer
    Public Property lavIdVehiculo As Integer
    Public Property lavIdPaquete As Integer
    Public Property lavExtras As String
    Public Property lavLavador As String
    Public Property lavMonto As Decimal
    Public Property lavFechaPago As Date
    Public Property lavPagadoA As String

    Public Overridable Property tblCliente As tblCliente
    Public Overridable Property tblVehiculo As tblVehiculo
    Public Overridable Property tblPaquetes As tblPaquetes

End Class
