'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblPaquetes
    Public Property paqId As Integer
    Public Property paqNombre As String
    Public Property paqTipo As String
    Public Property paqDescripcion As String
    Public Property paqCosto As Decimal

    Public Overridable Property tblLavados As ICollection(Of tblLavados) = New HashSet(Of tblLavados)

End Class
