'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblVehiculo
    Public Property vehPlaca As Integer
    Public Property vehClienteId As Integer
    Public Property vehMarca As String
    Public Property vehSize As String

    Public Overridable Property tblCliente As tblCliente
    Public Overridable Property tblLavados As ICollection(Of tblLavados) = New HashSet(Of tblLavados)

End Class
