'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tblVehiculo
    Public Property vehPlaca As String
    Public Property vehClienteId As Integer
    Public Property vehMarca As String
    Public Property vehSize As String

End Class
